CREATE DATABASE IF NOT EXISTS spotifyapi CHARACTER SET utf8mb4 COLLATE utf8mb4_latvian_ci;

CREATE TABLE IF NOT EXISTS spotifyapi.authors(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
	followers INT NOT NULL,
	genre VARCHAR(255) NOT NULL,
	popularity INT NOT NULL);